### ISSUE TITLE
build error :Failed to create symlink

### ISSUE THREAD

**Issue by tmp-coder** [JasonQSY/6.035-compiler#2]
when i run './build.sh', i get 

```
Failed to create symlink C:\path\to\6.035-compiler\dist/antlr.jar to target C:\path\to\6.035-compiler\lib/antlr.jar
```

OS : win10

**Comment by JasonQSY** [comment]
The repo is only tested on OS X and linux. and I'm not active for this repo right now.

**Comment by tmp-coder** [comment]
i replace 
```
<symlink link="${dist}/antlr.jar" resource="${lib}/antlr.jar"
             overwrite="true" />
```

to 

```
<exec executable="cmd" os="Windows 10">
      <arg value="/c"/>
      <arg line="mklink /D ${dist}/antlr.jar ${lib}/antlr.jar"/>
    </exec>
```
,and it worked.

i think this maybe becouse  command of create symlink is defferent from linux/Mac OS in Windows platform. 

another things.

i forked a new repo from official repo https://github.com/6035/java-skeleton, but have no access permission of 'test' repo, so i'd like to know whether test set in your repo is comlete or not.

thanks to your reply!

**Comment by JasonQSY** [comment]
I don't remember where they come from. I think they can be complete but pretty old.

**Comment by tmp-coder** [comment]
ok,many many thanks!
